name: Pulumi
on:
  - pull_request 
permissions:
  id-token: write
  contents: read
jobs:
  check:
    name: Check
    runs-on: self-hosted
    steps: 
      - run: |
          if [ -z "$ARM_OIDC_TOKEN" ]; then
            echo "ARM_OIDC_TOKEN is not set"
          else
            echo "ARM_OIDC_TOKEN is set"
          fi

  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.0.2
        with:
          node-version-file: package.json
      - run: npm install
      - uses: pulumi/actions@v5
        with:
          command: preview
          stack-name: team-ce/lotctl
          upsert: true  
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}